CREATE SCHEMA IF NOT EXISTS WAREHOUSE;

CREATE TABLE IF NOT EXISTS WAREHOUSE.PRODUCTS
(
  ID UUID NOT NULL,
  WIDTH DOUBLE PRECISION NOT NULL,
  HEIGHT DOUBLE PRECISION NOT NULL,
  DEPTH DOUBLE PRECISION,
  WEIGHT DOUBLE PRECISION NOT NULL,
  FRAGILE BOOLEAN NOT NULL,
  QUANTITY INTEGER NOT NULL,
  CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);
COMMENT ON TABLE WAREHOUSE.PRODUCTS IS 'Содержит информацию о товарах на складе';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.ID IS 'Уникальный идентификатор';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.WIDTH IS 'Наименование товара';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.HEIGHT IS 'Описание товара';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.DEPTH IS 'Ссылка на картинку во внешнем хранилище или SVG';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.WEIGHT IS 'Статус остатка товара';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.FRAGILE IS 'Статус товара';
COMMENT ON COLUMN WAREHOUSE.PRODUCTS.QUANTITY IS 'Цена товара';