CREATE SCHEMA IF NOT EXISTS SHOPPING_STORE;

CREATE TABLE IF NOT EXISTS SHOPPING_STORE.PRODUCTS
(
  ID UUID NOT NULL,
  NAME VARCHAR(1000) NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  IMAGE_SRC VARCHAR(1000),
  QUANTITY_STATE VARCHAR(50) NOT NULL,
  STATE VARCHAR(50) NOT NULL,
  CATEGORY VARCHAR(50),
  PRICE NUMERIC(12, 2) NOT NULL,
  CONSTRAINT PK_PRODUCTS PRIMARY KEY (ID)
);
COMMENT ON TABLE SHOPPING_STORE.PRODUCTS IS 'Содержит информацию товарах';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.ID IS 'Уникальный идентификатор';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.NAME IS 'Наименование товара';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.DESCRIPTION IS 'Описание товара';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.IMAGE_SRC IS 'Ссылка на картинку во внешнем хранилище или SVG';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.QUANTITY_STATE IS 'Статус остатка товара';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.STATE IS 'Статус товара';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.CATEGORY IS 'Категория товара';
COMMENT ON COLUMN SHOPPING_STORE.PRODUCTS.PRICE IS 'Цена товара';